### ISSUE TITLE
Change treasurer title

### ISSUE THREAD

**Issue by seankwalker** [YaleComputerSociety/website#2]
https://github.com/yalecs/website/blob/7434baae987097d49241f60e02475667c38bb822/_data/members.json#L19

"Treasury Chair" or "Treasurer" sound better

**Comment by felipap** [comment]
Hi Sean

**Comment by seankwalker** [comment]
pls change

**Comment by seankwalker** [comment]
this is important for my reputation

**Comment by felipap** [comment]
Send a pull request bro I'm not home
