### ISSUE TITLE
Crop event photos to square in preview rather than scaling

### ISSUE THREAD

**Issue by ErikBoesen** [YaleComputerSociety/website#8]
Prefer square cropping to this:
<img src="https://user-images.githubusercontent.com/5923662/66858988-70caa500-ef58-11e9-8534-5a4c0332c63c.png">

**Comment by felipap** [comment]
Hey Erik, let me know if you have any questions while fixing these issues. 👍🏼

**Comment by ErikBoesen** [comment]
@felipap Can you assign this and the other issues to me?

**Comment by felipap** [comment]
Sure!
